
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=false  enc_num_iters:int=1 --tag _1n0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=false  enc_num_iters:int=1 --tag _1n1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=false  enc_num_iters:int=1 --tag _1n2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=false  enc_num_iters:int=1 --tag _1n3
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=false  enc_num_iters:int=2 --tag _2n0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=false  enc_num_iters:int=2 --tag _2n1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=false  enc_num_iters:int=2 --tag _2n2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=false  enc_num_iters:int=2 --tag _2n3
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=false  enc_num_iters:int=3 --tag _3n0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=false  enc_num_iters:int=3 --tag _3n1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=false  enc_num_iters:int=3 --tag _3n2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=false  enc_num_iters:int=3 --tag _3n3
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=true  enc_num_iters:int=1 --tag _1a0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=true  enc_num_iters:int=1 --tag _1a1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=true  enc_num_iters:int=1 --tag _1a2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=true  enc_num_iters:int=1 --tag _1a3
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=true  enc_num_iters:int=2 --tag _2a0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=true  enc_num_iters:int=2 --tag _2a1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=true  enc_num_iters:int=2 --tag _2a2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=true  enc_num_iters:int=2 --tag _2a3
./test_chinese.py $1 refine_iters:int=0 decode_ar:bool=true  enc_num_iters:int=3 --tag _3a0
./test_chinese.py $1 refine_iters:int=1 decode_ar:bool=true  enc_num_iters:int=3 --tag _3a1
./test_chinese.py $1 refine_iters:int=2 decode_ar:bool=true  enc_num_iters:int=3 --tag _3a2
./test_chinese.py $1 refine_iters:int=3 decode_ar:bool=true  enc_num_iters:int=3 --tag _3a3